#!/bin/bash
STAR WARS

Episode IV

A NEW HOPE

It should then print the following:

Opening crawl


A long time ago in a galaxy far, far away....

It is a period of civil war. Rebel
spaceships, striking from a hidden base, have won their first victory against
the evil Galactic Empire.

During the battle, Rebel spies managed to steal secret plans to the Empire's
ultimate weapon, the DEATH STAR, an armored space station with enough power to
destroy an entire planet.
